### PR TITLE
Structure Project for setuptools and Expand Backwards Compatability

### LINKED ISSUE #12: Structure project for setuptools.
Structure project for setuptools, and general pip installation and initialization.

### LINKED ISSUE #22: Upgrade everything on the project for Python 3.5+
Upgrade setup, tests, and code to be compatible with Python 3.5+.

### PR DESCRIPTION
**Pull request by eauel**
This PR restructures the genomics-benchmarks project for setuptools, which will allow the tool to be packaged and distributed on PyPI. Additionally, the genomics-benchmark executable and package names have been updated to match the GitHub repository name: genomics-benchmarks. Backwards compatibility has also been improved, and the package should now support Python versions 2.7, 3.4, 3.5, and 3.6.

The method for generating a default generation file has been updated so that it will work properly whether running genomics-benchmarks from the source code or when installed as a package from pip.

Unit tests for config.py have also been updated to point to the new default configuration file path. This path changed due to placing the default config file in the package directory, so that it will be included with the package.

This PR resolves #12 and resolves #22.

### CODE REVIEW

**Comment by eauel** [comment]
@ebegoli @alimanfoo 

With this PR, I currently have the package name for PyPI set as "genomics-benchmarks" to match the GitHub repository name. I also changed the entry point script from "genomics-benchmark" to "genomics-benchmarks." However, the README file states that the package name and executable name will be "genomics-benchmark."

I have two questions:
(1) Should the entry-point script be called genomics-benchmark or genomics-benchmarks?
(2) Will the PyPI package be named as genomics-benchmark or genomics-benchmarks?

Here is what the README file currently says:

image

**Comment by ebegoli** [comment]
Eric,

You change it to what makes sense in terms of consistency and following the
general best practices.

What we did so far was an effort to just get started, with high likelihood
that we missed or misrepresented something.

Thank you,
Edmon

**Comment by eauel** [comment]
Thanks Edmon, I will change the package name and executable name to genomics-benchmarks for consistency with the repository's name.

-Eric

**Comment by eauel** [comment]
Updated to allow for backwards compatibility for older versions of Python.

Ready for merge.

**Pull request merged**
